services:
  inventory-database-test:
    container_name: inventory-database-test
    # using docker file in fake fir
    build:
       dockerfile: fake/Dockerfile
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      # using different port to not have conflict or dont even map port
      - "5435:5432"

# no volume, data go wipe if kill and load the default fake data when created
#
